name: Docker Image CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          # The name of the image you would like to push
          name: "giffel/scipy"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,another"
